Repository Requisitos-de-Software/2020.1-Mia-Ajuda, pull requests merged in 2020-09, with the labels that each got.

#14 Novas paginas adicionadas.
  .github/issue-template.md
  .github/pull_request_template.md
  README.md
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/assets/crewPhotos/ailamarPhoto.jpg
  docs/assets/crewPhotos/danilloPhoto.jpg
  docs/assets/crewPhotos/matheusPhoto.jpg
  docs/assets/crewPhotos/pauloPhoto.jpg
  docs/assets/crewPhotos/pedroPhoto.jpg
  docs/assets/logo/miaAjudaLogo&Name.png
  docs/assets/logo/miaAjudaLogo.png
  docs/docs/assets/styles/home.css
  docs/index.html
  docs/pages/Methodology/Images/issues.png
  docs/pages/Methodology/Images/labels.png
  docs/pages/Methodology/Methodology.md
  docs/pages/images/cronograma.png
  docs/pages/images/miaAjudaLogo&Name.png
  docs/pages/images/miaAjudaLogo.png
  docs/pages/policy/images/IssueNumber.jpg
  docs/pages/policy/images/folderExample.png
  docs/pages/policy/policy.md
  docs/pages/teamTools/Images/DiscordLogo.png
  docs/pages/teamTools/Images/TelegramLogo.png
  docs/pages/teamTools/Images/VisualSudioCode.png
  docs/pages/teamTools/Images/zenhub-black.png
  docs/pages/teamTools/teamTools.md
Labels: Documentação, Média

#16 [#5] Added schedule documents
  docs/_sidebar.md
  docs/pages/schedule/Images/cronograma.png
  docs/pages/schedule/schedule.md
Labels: Documentação, Média

#17 Consertando as imagens que não estavam aparecendo na wiki
  docs/pages/Methodology/Methodology.md
  docs/pages/policy/policy.md
  docs/pages/schedule/schedule.md
  docs/pages/teamTools/teamTools.md
Labels: Média, bug

#20 Images change, Added github in teamTools
  docs/_sidebar.md
  docs/pages/planning/teamTools/Images/DiscordLogo.png
  docs/pages/planning/teamTools/Images/gitHub.png
  docs/pages/planning/teamTools/Images/zenhub-black.png
  docs/pages/planning/teamTools/teamTools.md
  docs/pages/teamTools/teamTools.md
Labels: Baixa, Documentação, enhancement

#21 resolving conflits of pull request #19
  docs/pages/Methodology/Methodology.md
  docs/pages/planning/Methodology/Methodology.md
  docs/pages/planning/schedule/schedule.md
  docs/pages/planning/teamTools/teamTools.md
  docs/pages/schedule/schedule.md
Labels: Documentação, Média

#27 Fixed collapse of sidebar for the planning page.
  docs/css/index.css
  docs/index.html
  docs/pages/planning/planning.md
  docs/pages/presentations/presentations.md
Labels: Baixa, Documentação, bug

#28 Presentations page
  docs/_sidebar.md
  docs/assets/crewPhotos/ailamarPhoto.jpg
  docs/assets/crewPhotos/danilloPhoto.jpg
  docs/assets/crewPhotos/matheusPhoto.jpg
  docs/assets/crewPhotos/pauloPhoto.jpg
  docs/assets/crewPhotos/pedroPhoto.jpg
  docs/css/index.css
  docs/index.html
  docs/pages/planning/planning.md
  docs/pages/presentations/presentations.md
Labels: Baixa, Documentação, Média
